(coq.theory
 (name elpi)
 (package rocq-elpi)
 (plugins rocq-elpi.elpi)
 (theories elpi_elpi))

(rule
 (target elpi.v)
 (deps
  (glob_files elpi.v.in)
  %{workspace_root}/_build/install/default/lib/rocq-elpi/elpi/elpi_plugin.cmxs
  %{workspace_root}/_build/install/default/lib/rocq-elpi/elpi/elpi_plugin.cma)
 (action
  (with-stdout-to %{target}
   (run rocq_elpi_optcomp "%{coq:version.major}.%{coq:version.minor}" elpi.v.in))))

(include_subdirs qualified)
